version: '2'

services:
  orders-front:
    build:
      context: ../../envoyproxy
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ../../envoyproxy/orders-front.yaml:/etc/front-envoy.yaml
    expose:
      - "80"
    ports:
      - '8181:80'
      - '8001:8001'
  front-end:
    image: gfads/front-end:rbinder
    hostname: front-end
    restart: always
    cap_drop:
      - all
    read_only: true
  edge-router:
    image: weaveworksdemos/edge-router:0.1.1
    ports:
      - '80:80'
      - '8080:8080'
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    tmpfs:
      - /var/run:rw,noexec,nosuid
    hostname: edge-router
    restart: always
  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  carts:
    image: gfads/carts:ldpreload
    hostname: carts
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
  carts-db:
    image: mongo:3.4
    hostname: carts-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  carts-envoy:
    build:
      context: ../../envoyproxy
      dockerfile: Dockerfile-service-envoy
    environment:
      - SERVICE_NAME=carts
    volumes:
      - ../../envoyproxy/carts-envoy.yaml:/etc/envoy/envoy.yaml
  orders:
    image: gfads/orders:ldpreload
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    volumes:
      - ../../envoyproxy/orders-envoy.yaml:/etc/orders-envoy.yaml
    extra_hosts:
      - 'user:$ORDERS_ENVOY_IP'
      - 'carts:$ORDERS_ENVOY_IP'
      - 'shipping:$ORDERS_ENVOY_IP'
      - 'payment:$ORDERS_ENVOY_IP'
  orders-db:
    image: mongo:3.4
    hostname: orders-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  orders-envoy:
    build:
      context: ../../envoyproxy
      dockerfile: Dockerfile-service-envoy
    environment:
      - SERVICE_NAME=orders
    volumes:
      - ../../envoyproxy/orders-envoy.yaml:/etc/envoy/envoy.yaml
  shipping:
    image: gfads/shipping:ldpreload
    hostname: shipping
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
  shipping-envoy:
    build:
      context: ../../envoyproxy
      dockerfile: Dockerfile-service-envoy
    environment:
      - SERVICE_NAME=shipping
    volumes:
      - ../../envoyproxy/shipping-envoy.yaml:/etc/envoy/envoy.yaml
  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  rabbitmq:
    image: rabbitmq:3.6.8
    hostname: rabbitmq
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
  payment:
    image: gfads/payment:ldpreload
    hostname: payment
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
  payment-envoy:
    build:
      context: ../../envoyproxy
      dockerfile: Dockerfile-service-envoy
    environment:
      - SERVICE_NAME=payment
    volumes:
      - ../../envoyproxy/payment-envoy.yaml:/etc/envoy/envoy.yaml
  user:
    image: gfads/user:ldpreload
    hostname: user
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - MONGO_HOST=user-db:27017
  user-db:
    image: weaveworksdemos/user-db:0.4.0
    hostname: user-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  user-envoy:
    build:
      context: ../../envoyproxy
      dockerfile: Dockerfile-service-envoy
    environment:
      - SERVICE_NAME=user
    volumes:
      - ../../envoyproxy/user-envoy.yaml:/etc/envoy/envoy.yaml
  zipkin:
    image: openzipkin/zipkin
    expose:
      - "9411"
    ports:
      - "9411:9411"
