version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end
    networks:
      - weavedemo_backoffice
    hostname: front-end
    restart: always
    cap_drop:
      - all
    read_only: true
  edge-router:
    image: weaveworksdemos/edge-router
    networks:
      - weavedemo_backoffice
    ports:
      - '80:80'
      - '8080:8080'
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    tmpfs:
      - /var/run:rw,noexec,nosuid
    hostname: edge-router
    restart: always
  catalogue:
    #image: weaveworksdemos/catalogue
    image: gfads/catalogue:5a476e87
    networks:
      - weavedemo_backoffice
    hostname: catalogue
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - ZIPKIN=http://zipkin:9411/api/v1/spans
  catalogue-db:
    image: weaveworksdemos/catalogue-db
    networks:
      - weavedemo_backoffice
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  carts:
    image: weaveworksdemos/carts
    networks:
      - weavedemo_backoffice
    hostname: carts
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
      - ZIPKIN=zipkin
  carts-db:
    image: mongo
    networks:
      - weavedemo_backoffice
    hostname: carts-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  orders:
    image: weaveworksdemos/orders
    networks:
      - weavedemo_backoffice
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
    environment:
      - ZIPKIN=zipkin
  orders-db:
    image: mongo
    networks:
      - weavedemo_backoffice
    hostname: orders-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  shipping:
    image: weaveworksdemos/shipping
    networks:
      - weavedemo_backoffice
    hostname: shipping
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
      - ZIPKIN=zipkin
  queue-master:
    #image: weaveworksdemos/queue-master
    image: gfads/queue-master
    networks:
      - weavedemo_backoffice
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    #cap_drop:
    #  - all
    #cap_add:
    #  - NET_BIND_SERVICE
    #read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  rabbitmq:
    image: rabbitmq:3.6.8-alpine
    networks:
      - weavedemo_backoffice
    hostname: rabbitmq
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
  payment:
    #image: weaveworksdemos/payment
    image: gfads/payment:a440cf61
    networks:
      - weavedemo_backoffice
    hostname: payment
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - ZIPKIN=http://zipkin:9411/api/v1/spans
  user:
    #image: weaveworksdemos/user
    image: gfads/user:10b11fe9
    networks:
      - weavedemo_backoffice
    hostname: user
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - MONGO_HOST=user-db:27017
      - ZIPKIN=http://zipkin:9411/api/v1/spans
  user-db:
    image: weaveworksdemos/user-db
    networks:
      - weavedemo_backoffice
    hostname: user-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  zipkin:
    image: openzipkin/zipkin
    networks:
      - weavedemo_backoffice
    hostname: zipkin
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    ports:
      - "9411:9411"
  #user-sim:
  #  image: weaveworksdemos/load-test
  #  networks:
  #    - weavedemo_backoffice
  #  cap_drop:
  #    - all
  #  read_only: true
  #  hostname: user-simulator
  #  command: "-d 60 -r 200 -c 2 -h edge-router"


networks:
  weavedemo_backoffice:
    driver: bridge
